-- ═══════════════════════════════════════════════════════
-- NicheHub — Schema (matches live Supabase DB)
-- ═══════════════════════════════════════════════════════

-- SITES — master registry
-- id is a UUID auto-generated by Supabase; slug is the text identifier used in config/code.
CREATE TABLE sites (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  slug        text NOT NULL UNIQUE,
  name        text NOT NULL,
  domain      text NOT NULL DEFAULT '',
  language    text NOT NULL DEFAULT 'en',
  direction   text NOT NULL DEFAULT 'ltr',
  created_at  timestamptz DEFAULT now()
);

-- CATEGORIES
CREATE TABLE categories (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id     uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name        text NOT NULL,
  slug        text NOT NULL,
  description text DEFAULT '',
  created_at  timestamptz DEFAULT now(),
  UNIQUE(site_id, slug)
);

-- PRODUCTS
CREATE TABLE products (
  id            uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id       uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name          text NOT NULL,
  slug          text NOT NULL,
  description   text DEFAULT '',
  affiliate_url text DEFAULT '',
  image_url     text DEFAULT '',
  price         text DEFAULT '',
  merchant      text DEFAULT '',
  score         real CHECK (score >= 0 AND score <= 10),
  featured      boolean DEFAULT false,
  status        text NOT NULL DEFAULT 'active'
                CHECK (status IN ('draft', 'active', 'archived')),
  category_id   uuid REFERENCES categories(id) ON DELETE SET NULL,
  cta_text      text DEFAULT '',
  deal_text     text DEFAULT '',
  deal_expires_at timestamptz,
  created_at    timestamptz DEFAULT now(),
  UNIQUE(site_id, slug)
);

-- CONTENT
CREATE TABLE content (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id     uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  title       text NOT NULL,
  slug        text NOT NULL,
  body        text DEFAULT '',
  excerpt     text DEFAULT '',
  featured_image text DEFAULT '',
  type        text NOT NULL DEFAULT 'article'
              CHECK (type IN (
                'article', 'review', 'comparison', 'guide', 'blog'
              )),
  status      text NOT NULL DEFAULT 'draft'
              CHECK (status IN ('draft', 'review', 'published', 'archived')),
  category_id uuid REFERENCES categories(id) ON DELETE SET NULL,
  tags        text[] DEFAULT '{}',
  author      text,
  publish_at  timestamptz,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now(),
  UNIQUE(site_id, slug)
);

-- CONTENT <-> PRODUCTS (many-to-many)
CREATE TABLE content_products (
  content_id  uuid NOT NULL REFERENCES content(id) ON DELETE CASCADE,
  product_id  uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  role        text DEFAULT 'hero'
              CHECK (role IN ('hero', 'featured', 'related', 'vs-left', 'vs-right')),
  PRIMARY KEY (content_id, product_id)
);

-- NEWSLETTER SUBSCRIBERS
CREATE TABLE newsletter_subscribers (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id     uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  email       text NOT NULL,
  status      text NOT NULL DEFAULT 'active'
              CHECK (status IN ('active', 'unsubscribed')),
  created_at  timestamptz DEFAULT now(),
  UNIQUE(site_id, email)
);

-- AFFILIATE CLICK TRACKING
CREATE TABLE affiliate_clicks (
  id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id         uuid REFERENCES sites(id) ON DELETE SET NULL,
  product_name    text DEFAULT '',
  affiliate_url   text DEFAULT '',
  content_slug    text DEFAULT '',
  referrer        text DEFAULT '',
  created_at      timestamptz DEFAULT now()
);

-- SCHEDULED JOBS — ledger for all scheduled operations
CREATE TABLE scheduled_jobs (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  site_id     uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  job_type    text NOT NULL
              CHECK (job_type IN ('publish_content', 'activate_product', 'archive_content', 'archive_product', 'custom')),
  target_id   uuid NOT NULL,
  scheduled_for timestamptz NOT NULL,
  status      text NOT NULL DEFAULT 'pending'
              CHECK (status IN ('pending', 'executed', 'failed', 'cancelled')),
  payload     jsonb DEFAULT '{}',
  executed_at timestamptz,
  error       text,
  created_at  timestamptz DEFAULT now()
);

-- ═══════════════════════════════════════════════════════
-- INDEXES
-- ═══════════════════════════════════════════════════════

CREATE INDEX idx_categories_site        ON categories(site_id);
CREATE INDEX idx_products_site          ON products(site_id);
CREATE INDEX idx_products_site_slug     ON products(site_id, slug);
CREATE INDEX idx_products_site_featured ON products(site_id, featured)
  WHERE featured = true;
CREATE INDEX idx_content_site           ON content(site_id);
CREATE INDEX idx_content_site_status    ON content(site_id, status);
CREATE INDEX idx_content_site_slug      ON content(site_id, slug);
CREATE INDEX idx_content_site_type      ON content(site_id, type);
CREATE INDEX idx_content_updated        ON content(site_id, updated_at DESC)
  WHERE status = 'published';
CREATE INDEX idx_clicks_site            ON affiliate_clicks(site_id);
CREATE INDEX idx_clicks_created         ON affiliate_clicks(created_at DESC);
CREATE INDEX idx_newsletter_site        ON newsletter_subscribers(site_id);
CREATE INDEX idx_scheduled_jobs_site    ON scheduled_jobs(site_id);
CREATE INDEX idx_scheduled_jobs_pending ON scheduled_jobs(status, scheduled_for)
  WHERE status = 'pending';

-- Full-text search indexes (GIN)
CREATE INDEX idx_content_fts_title   ON content USING gin (to_tsvector('simple', title));
CREATE INDEX idx_content_fts_excerpt ON content USING gin (to_tsvector('simple', excerpt));
CREATE INDEX idx_products_fts_name   ON products USING gin (to_tsvector('simple', name));
CREATE INDEX idx_products_fts_desc   ON products USING gin (to_tsvector('simple', description));

-- ═══════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ═══════════════════════════════════════════════════════

ALTER TABLE sites             ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories        ENABLE ROW LEVEL SECURITY;
ALTER TABLE products          ENABLE ROW LEVEL SECURITY;
ALTER TABLE content           ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_products  ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_clicks  ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_jobs        ENABLE ROW LEVEL SECURITY;

-- Public read policies (anon key)
CREATE POLICY "public_read_sites"
  ON sites FOR SELECT USING (true);

CREATE POLICY "public_read_categories"
  ON categories FOR SELECT USING (true);

CREATE POLICY "public_read_active_products"
  ON products FOR SELECT USING (status = 'active');

CREATE POLICY "public_read_published_content"
  ON content FOR SELECT USING (status = 'published');

CREATE POLICY "public_read_content_products"
  ON content_products FOR SELECT USING (true);

-- Anonymous write policies (public actions)
CREATE POLICY "public_insert_clicks"
  ON affiliate_clicks FOR INSERT WITH CHECK (true);

CREATE POLICY "public_insert_newsletter"
  ON newsletter_subscribers FOR INSERT WITH CHECK (true);

-- Note: All admin operations use the Supabase service key (bypasses RLS).

-- ═══════════════════════════════════════════════════════
-- TRIGGERS
-- ═══════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER content_updated_at
  BEFORE UPDATE ON content
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ═══════════════════════════════════════════════════════
-- SEED: arabic-tools site
-- ═══════════════════════════════════════════════════════

INSERT INTO sites (slug, name, domain, language, direction)
VALUES ('arabic-tools', 'Arabic Tools', 'arabic-tools.example.com', 'ar', 'rtl');

-- ═══════════════════════════════════════════════════════
-- SEED: crypto-tools site
-- ═══════════════════════════════════════════════════════

INSERT INTO sites (slug, name, domain, language, direction)
VALUES ('crypto-tools', 'Crypto Tools', 'crypto-tools.example.com', 'en', 'ltr');

-- Crypto categories
WITH crypto AS (SELECT id FROM sites WHERE slug = 'crypto-tools')
INSERT INTO categories (site_id, name, slug) VALUES
  ((SELECT id FROM crypto), 'Exchanges', 'exchanges'),
  ((SELECT id FROM crypto), 'Wallets', 'wallets'),
  ((SELECT id FROM crypto), 'DeFi', 'defi'),
  ((SELECT id FROM crypto), 'Mining', 'mining'),
  ((SELECT id FROM crypto), 'NFTs', 'nfts'),
  ((SELECT id FROM crypto), 'Education', 'education');

-- Crypto products (UUIDs auto-generated; category_id resolved via slug)
WITH crypto AS (SELECT id FROM sites WHERE slug = 'crypto-tools')
INSERT INTO products (site_id, name, slug, description, affiliate_url, image_url, price, merchant, score, featured, status, category_id) VALUES
  ((SELECT id FROM crypto), 'Binance', 'binance',
   'World''s largest crypto exchange by trading volume. Low fees and 350+ coins supported.',
   'https://www.binance.com/ref/example', '', 'Free to join', 'Binance', 9.2, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'exchanges')),
  ((SELECT id FROM crypto), 'Coinbase', 'coinbase',
   'Beginner-friendly US-based exchange with strong regulatory compliance.',
   'https://www.coinbase.com/ref/example', '', 'Free to join', 'Coinbase', 8.5, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'exchanges')),
  ((SELECT id FROM crypto), 'Ledger Nano X', 'ledger-nano-x',
   'Premium Bluetooth-enabled hardware wallet supporting 5,500+ coins.',
   'https://www.ledger.com/ref/example', '', '$149', 'Ledger', 9.0, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'wallets')),
  ((SELECT id FROM crypto), 'Trezor Model T', 'trezor-model-t',
   'Open-source hardware wallet with touchscreen and advanced security features.',
   'https://www.trezor.io/ref/example', '', '$219', 'Trezor', 8.8, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'wallets')),
  ((SELECT id FROM crypto), 'Aave', 'aave',
   'Leading DeFi lending protocol. Earn interest or borrow against your crypto.',
   'https://aave.com/ref/example', '', 'Free', 'Aave', 8.7, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'defi')),
  ((SELECT id FROM crypto), 'NiceHash', 'nicehash',
   'Marketplace for mining hash power. Mine or buy hash power easily.',
   'https://www.nicehash.com/ref/example', '', 'Free', 'NiceHash', 7.5, false, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'mining')),
  ((SELECT id FROM crypto), 'OpenSea', 'opensea',
   'Largest NFT marketplace for buying, selling, and discovering digital assets.',
   'https://opensea.io/ref/example', '', 'Free', 'OpenSea', 8.0, false, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'nfts')),
  ((SELECT id FROM crypto), 'Kraken', 'kraken',
   'Established US exchange with advanced trading features and staking.',
   'https://www.kraken.com/ref/example', '', 'Free to join', 'Kraken', 8.6, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'exchanges'));

-- Crypto content
WITH crypto AS (SELECT id FROM sites WHERE slug = 'crypto-tools')
INSERT INTO content (site_id, title, slug, body, excerpt, type, status, category_id, tags, author) VALUES
  ((SELECT id FROM crypto),
   'Best Crypto Exchanges in 2026: Complete Comparison',
   'best-crypto-exchanges-2026',
   '<h2>Top Crypto Exchanges Compared</h2><p>Choosing the right crypto exchange is one of the most important decisions for any trader.</p>',
   'Compare the top cryptocurrency exchanges by fees, security, and features.',
   'comparison', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'exchanges'),
   ARRAY['exchanges', 'comparison', 'trading'], 'CryptoTools Team'),
  ((SELECT id FROM crypto),
   'Ledger Nano X Review: Is It Worth the Price?',
   'ledger-nano-x-review',
   '<h2>Ledger Nano X Review</h2><p>The Ledger Nano X is one of the most popular hardware wallets on the market.</p>',
   'In-depth review of the Ledger Nano X hardware wallet.',
   'review', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'wallets'),
   ARRAY['wallets', 'hardware-wallet', 'security'], 'CryptoTools Team'),
  ((SELECT id FROM crypto),
   'Beginner''s Guide to DeFi: What You Need to Know',
   'beginners-guide-to-defi',
   '<h2>What is DeFi?</h2><p>Decentralized Finance (DeFi) refers to financial services built on blockchain technology.</p>',
   'Learn the fundamentals of Decentralized Finance.',
   'guide', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'defi'),
   ARRAY['defi', 'guide', 'beginners'], 'CryptoTools Team'),
  ((SELECT id FROM crypto),
   'How to Choose a Crypto Wallet in 2026',
   'how-to-choose-crypto-wallet',
   '<h2>Choosing the Right Crypto Wallet</h2><p>Your crypto wallet is the gateway to the blockchain.</p>',
   'A comprehensive guide to choosing the best crypto wallet.',
   'article', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'crypto-tools' AND c.slug = 'wallets'),
   ARRAY['wallets', 'security', 'guide'], 'CryptoTools Team');

-- Arabic-tools categories
WITH arabic AS (SELECT id FROM sites WHERE slug = 'arabic-tools')
INSERT INTO categories (site_id, name, slug, description) VALUES
  ((SELECT id FROM arabic), 'أدوات الكتابة', 'writing-tools', 'أفضل أدوات الكتابة العربية والتحرير'),
  ((SELECT id FROM arabic), 'أدوات الترجمة', 'translation-tools', 'أدوات ترجمة احترافية للغة العربية'),
  ((SELECT id FROM arabic), 'أدوات التعليم', 'education-tools', 'منصات وأدوات تعلم اللغة العربية'),
  ((SELECT id FROM arabic), 'أدوات التصميم', 'design-tools', 'أدوات تصميم تدعم الخط العربي'),
  ((SELECT id FROM arabic), 'أدوات SEO', 'seo-tools', 'أدوات تحسين محركات البحث للمحتوى العربي');

-- Arabic-tools products
WITH arabic AS (SELECT id FROM sites WHERE slug = 'arabic-tools')
INSERT INTO products (site_id, name, slug, description, affiliate_url, price, merchant, score, featured, status, category_id, cta_text) VALUES
  ((SELECT id FROM arabic), 'Grammarly Arabic', 'grammarly-arabic',
   'أداة تدقيق لغوي متقدمة تدعم اللغة العربية مع اقتراحات ذكية.',
   'https://www.grammarly.com/ref/example', 'مجاني / $12 شهرياً', 'Grammarly', 8.5, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'writing-tools'),
   'جرّب مجاناً'),
  ((SELECT id FROM arabic), 'DeepL Translator', 'deepl-translator',
   'أفضل مترجم آلي بالذكاء الاصطناعي مع دعم ممتاز للعربية.',
   'https://www.deepl.com/ref/example', 'مجاني / $8.74 شهرياً', 'DeepL', 9.0, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'translation-tools'),
   'ترجم الآن'),
  ((SELECT id FROM arabic), 'Duolingo Arabic', 'duolingo-arabic',
   'تعلم اللغة العربية مجاناً مع دروس تفاعلية وممتعة.',
   'https://www.duolingo.com/ref/example', 'مجاني / $6.99 شهرياً', 'Duolingo', 8.0, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'education-tools'),
   'ابدأ التعلم'),
  ((SELECT id FROM arabic), 'Canva Arabic', 'canva-arabic',
   'منصة تصميم سهلة مع قوالب ودعم كامل للخط العربي.',
   'https://www.canva.com/ref/example', 'مجاني / $12.99 شهرياً', 'Canva', 9.2, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'design-tools'),
   'صمّم مجاناً'),
  ((SELECT id FROM arabic), 'Ahrefs', 'ahrefs',
   'أداة SEO احترافية لتحليل الكلمات المفتاحية والروابط الخلفية.',
   'https://ahrefs.com/ref/example', '$99 شهرياً', 'Ahrefs', 9.1, true, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'seo-tools'),
   'جرّب Ahrefs'),
  ((SELECT id FROM arabic), 'Google Translate', 'google-translate',
   'خدمة ترجمة مجانية من جوجل تدعم أكثر من 100 لغة.',
   'https://translate.google.com', 'مجاني', 'Google', 7.5, false, 'active',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'translation-tools'),
   'استخدم الآن');

-- Arabic-tools content
WITH arabic AS (SELECT id FROM sites WHERE slug = 'arabic-tools')
INSERT INTO content (site_id, title, slug, body, excerpt, type, status, category_id, tags, author) VALUES
  ((SELECT id FROM arabic),
   'أفضل أدوات الترجمة العربية في 2026: مقارنة شاملة',
   'best-arabic-translation-tools-2026',
   '<h2>مقارنة أفضل أدوات الترجمة</h2><p>اختيار أداة الترجمة المناسبة أمر بالغ الأهمية للمحتوى العربي عالي الجودة.</p>',
   'قارن بين أفضل أدوات الترجمة العربية من حيث الدقة والسعر والميزات.',
   'comparison', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'translation-tools'),
   ARRAY['ترجمة', 'مقارنة', 'أدوات'], 'فريق Arabic Tools'),
  ((SELECT id FROM arabic),
   'مراجعة Canva للتصميم العربي: هل تستحق الاشتراك؟',
   'canva-arabic-review',
   '<h2>مراجعة Canva</h2><p>Canva هي واحدة من أشهر منصات التصميم في العالم مع دعم ممتاز للخط العربي.</p>',
   'مراجعة شاملة لمنصة Canva ودعمها للتصميم باللغة العربية.',
   'review', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'design-tools'),
   ARRAY['تصميم', 'مراجعة', 'canva'], 'فريق Arabic Tools'),
  ((SELECT id FROM arabic),
   'دليل المبتدئين لتحسين SEO للمحتوى العربي',
   'beginners-guide-arabic-seo',
   '<h2>ما هو SEO؟</h2><p>تحسين محركات البحث (SEO) هو عملية تحسين موقعك ليظهر في نتائج البحث.</p>',
   'تعلم أساسيات تحسين محركات البحث للمحتوى العربي.',
   'guide', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'seo-tools'),
   ARRAY['seo', 'دليل', 'مبتدئين'], 'فريق Arabic Tools'),
  ((SELECT id FROM arabic),
   'كيف تختار أفضل أداة كتابة عربية في 2026',
   'how-to-choose-arabic-writing-tool',
   '<h2>اختيار أداة الكتابة المناسبة</h2><p>أداة الكتابة الجيدة تساعدك على إنتاج محتوى عربي احترافي بسرعة.</p>',
   'دليل شامل لاختيار أفضل أداة كتابة باللغة العربية.',
   'article', 'published',
   (SELECT c.id FROM categories c JOIN sites s ON c.site_id = s.id WHERE s.slug = 'arabic-tools' AND c.slug = 'writing-tools'),
   ARRAY['كتابة', 'أدوات', 'دليل'], 'فريق Arabic Tools');

-- Arabic-tools content-products links
WITH
  tr AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'arabic-tools' AND co.slug = 'best-arabic-translation-tools-2026'),
  cr AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'arabic-tools' AND co.slug = 'canva-arabic-review'),
  sg AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'arabic-tools' AND co.slug = 'beginners-guide-arabic-seo'),
  wg AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'arabic-tools' AND co.slug = 'how-to-choose-arabic-writing-tool'),
  deepl    AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'deepl-translator'),
  gtrans   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'google-translate'),
  canva    AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'canva-arabic'),
  ahrefs   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'ahrefs'),
  grammarly AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'arabic-tools' AND p.slug = 'grammarly-arabic')
INSERT INTO content_products (content_id, product_id, role) VALUES
  ((SELECT id FROM tr), (SELECT id FROM deepl),    'hero'),
  ((SELECT id FROM tr), (SELECT id FROM gtrans),   'hero'),
  ((SELECT id FROM cr), (SELECT id FROM canva),    'hero'),
  ((SELECT id FROM sg), (SELECT id FROM ahrefs),   'hero'),
  ((SELECT id FROM wg), (SELECT id FROM grammarly), 'hero');

-- Crypto content-products links
WITH
  ea AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'crypto-tools' AND co.slug = 'best-crypto-exchanges-2026'),
  lr AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'crypto-tools' AND co.slug = 'ledger-nano-x-review'),
  dg AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'crypto-tools' AND co.slug = 'beginners-guide-to-defi'),
  wg AS (SELECT co.id FROM content co JOIN sites s ON co.site_id = s.id WHERE s.slug = 'crypto-tools' AND co.slug = 'how-to-choose-crypto-wallet'),
  binance  AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'binance'),
  coinbase AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'coinbase'),
  ledger   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'ledger-nano-x'),
  trezor   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'trezor-model-t'),
  aave     AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'aave'),
  kraken   AS (SELECT p.id FROM products p JOIN sites s ON p.site_id = s.id WHERE s.slug = 'crypto-tools' AND p.slug = 'kraken')
INSERT INTO content_products (content_id, product_id, role) VALUES
  ((SELECT id FROM ea), (SELECT id FROM binance),  'hero'),
  ((SELECT id FROM ea), (SELECT id FROM coinbase), 'hero'),
  ((SELECT id FROM ea), (SELECT id FROM kraken),   'hero'),
  ((SELECT id FROM lr), (SELECT id FROM ledger),   'hero'),
  ((SELECT id FROM lr), (SELECT id FROM trezor),   'hero'),
  ((SELECT id FROM dg), (SELECT id FROM aave),     'hero'),
  ((SELECT id FROM wg), (SELECT id FROM ledger),   'hero'),
  ((SELECT id FROM wg), (SELECT id FROM trezor),   'hero');
