-- ═══════════════════════════════════════════════════════
-- DB-09: This file is intentionally empty in the repo.
-- ═══════════════════════════════════════════════════════
--
-- The canonical schema is defined by the migration files in
-- supabase/migrations/. A full snapshot is generated as a CI
-- artifact and is NOT committed to the repo.
--
-- To generate a local snapshot:
--   pg_dump --schema-only --no-owner --no-privileges \
--     -d "$SUPABASE_DB_URL" > supabase/schema.sql
--
-- See docs/migration-safety.md for the migration workflow.
