-- ═══════════════════════════════════════════════════════
-- DB-09: This file is intentionally empty in-repo.
-- ═══════════════════════════════════════════════════════
--
-- The canonical schema is defined by the 237+ migration files in
-- supabase/migrations/. A full schema snapshot is generated only
-- as a CI artifact (not committed) because committing it creates
-- noisy diffs on every migration and stale snapshots mislead reviewers.
--
-- To generate a local snapshot for inspection:
--   pg_dump --schema-only --no-owner --no-privileges \
--     -d "$SUPABASE_DB_URL" > supabase/schema.sql
--
-- See docs/migration-safety.md for the migration workflow.
