/**
 * Hand-curated app-level row types — NOT a generated artifact.
 *
 * These interfaces describe the subset of columns the application
 * code reads and are narrower / more opinionated than the raw
 * `Database['public']['Tables'][…]['Row']` types generated by the
 * Supabase CLI. They are imported by DAL helpers, server components,
 * and the admin UI wherever typed row objects are needed without the
 * full Insert/Update generics.
 *
 * Source of truth: this file is hand-edited.  Whenever a column is
 * added, renamed, or dropped in a migration, update the matching
 * interface here in the same PR.
 *
 * See also:
 *   - `types/supabase.ts`                — GENERATED `Database` type
 *                                          consumed by
 *                                          `createClient<Database>()`.
 *   - `scripts/check-schema-drift.sh`    — regenerates `types/supabase.ts`
 *                                          from the live DB; this file
 *                                          is intentionally NOT regenerated.
 */

// ── Affiliate Clicks ───────────────────────────────────────────────────

export interface AffiliateClickRow {
  id: string;
  click_id: string | null;
  click_ref: string | null;
  product_id: string | null;
  site_id: string;
  product_name: string;
  affiliate_url: string;
  content_slug: string;
  referrer: string;
  created_at: string;
}

export interface AffiliateLinkHealthRow {
  id: string;
  site_id: string;
  product_id: string;
  product_affiliate_link_id: string | null;
  url: string;
  network: string;
  last_probed_at: string | null;
  last_http_status: number | null;
  final_url: string | null;
  baseline_registrable_domain: string | null;
  latency_ms: number | null;
  consecutive_failures: number;
  failure_streak_started_at: string | null;
  classification: "healthy" | "broken" | "suspicious";
  created_at: string;
  updated_at: string;
}

export interface SiteRow {
  id: string;
  slug: string;
  name: string;
  domain: string;
  language: string;
  direction: "ltr" | "rtl";
  is_active: boolean;

  // Monetization
  monetization_type: "affiliate" | "ads" | "both";
  est_revenue_per_click: number;
  ad_config: Record<string, unknown>;

  // Theming
  theme: Record<string, unknown>;
  logo_url: string | null;
  favicon_url: string | null;

  // Navigation
  nav_items: { label: string; href: string; icon?: string }[];
  footer_nav: { label: string; href: string; icon?: string }[];

  // Features
  features: Record<string, boolean>;

  // SEO
  meta_title: string | null;
  meta_description: string | null;
  og_image_url: string | null;
  url_redirects?: Array<{
    source_path: string;
    destination_path: string;
    permanent?: boolean;
  }> | null;

  // Social links
  social_links: Record<string, string>;

  // Template / layout
  homepage_template: HomepageTemplate;
  product_card_style: ProductCardStyle;

  created_at: string;
  updated_at: string;
}

type HomepageTemplate =
  | "standard"
  | "cinematic"
  | "minimal"
  | "editorial"
  | "top10"
  | "compare"
  | "showcase";
type ProductCardStyle = "standard" | "compact" | "detailed";

export type TaxonomyType = "general" | "budget" | "occasion" | "recipient" | "brand" | "style";

export interface CategoryRow {
  id: string;
  site_id: string;
  name: string;
  slug: string;
  description: string;
  taxonomy_type: TaxonomyType;
  created_at: string;
}

export interface ProductRow {
  id: string;
  site_id: string;
  name: string;
  slug: string;
  description: string;
  affiliate_url: string;
  image_url: string;
  image_alt: string;
  price: string;
  price_amount: number | null;
  price_currency: string;
  merchant: string;
  score: number | null;
  featured: boolean;
  status: "draft" | "active" | "archived";
  category_id: string | null;
  category_ids?: string[] | null;
  cta_text: string;
  deal_text: string;
  deal_expires_at: string | null;
  pros: string;
  cons: string;
  /** ISO18-001: Optimistic locking version — incremented on every update. */
  version: number;
  created_at: string;
  updated_at: string;
}

export interface AuthorRow {
  id: string;
  site_id: string;
  name: string;
  slug: string;
  bio: string;
  photo_url: string;
  credentials: string;
  expertise: string[];
  social_links: Record<string, string>;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface ContentRow {
  id: string;
  site_id: string;
  title: string;
  slug: string;
  body: string;
  excerpt: string;
  featured_image: string;
  type: "article" | "review" | "comparison" | "guide" | "blog";
  status: "draft" | "review" | "published" | "scheduled" | "archived";
  category_id: string | null;
  tags: string[];
  author: string | null;
  author_id?: string | null;
  publish_at: string | null;
  meta_title: string | null;
  meta_description: string | null;
  og_image: string | null;
  body_previous: string | null;
  review_state: "draft" | "awaiting_edit" | "edited" | "published";
  /** SEC-13: true when this row was created or edited by an AI pipeline. DB default: false. */
  ai_generated?: boolean;
  /** SEC-13: timestamp of most recent human editorial review. */
  human_reviewed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface ContentProductRow {
  content_id: string;
  product_id: string;
  role: "hero" | "featured" | "related" | "vs-left" | "vs-right";
}

export interface PageRow {
  id: string;
  site_id: string;
  slug: string;
  title: string;
  body: string;
  is_published: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export type AdPlacementType = "sidebar" | "in_content" | "header" | "footer" | "between_posts";
export type AdProvider = "adsense" | "carbon" | "ethicalads" | "custom" | "image";

export interface AdPlacementRow {
  id: string;
  site_id: string;
  name: string;
  placement_type: AdPlacementType;
  provider: AdProvider;
  ad_code: string | null;
  config: Record<string, unknown>;
  is_active: boolean;
  priority: number;
  created_at: string;
}

// ── Module Registry ────────────────────────────────────────────────────

export interface SiteModuleRow {
  id: string;
  site_id: string;
  module_key: string;
  is_enabled: boolean;
  config: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

// ── Roles & Permissions ────────────────────────────────────────────────

type RoleName =
  | "owner"
  | "super_admin"
  | "admin"
  | "editor"
  | "author"
  | "moderator"
  | "seo_manager"
  | "translator"
  | "analyst";

export interface RoleRow {
  id: string;
  name: RoleName;
  label: string;
  description: string;
  is_system: boolean;
  created_at: string;
}

export type PermissionFeature =
  | "content"
  | "products"
  | "categories"
  | "seo"
  | "analytics"
  | "integrations"
  | "users"
  | "settings"
  | "themes"
  | "modules"
  | "scheduling"
  | "publishing"
  | "feature-flags"
  | "ads"
  | "pages"
  | "privacy"
  | "upload";

export type PermissionAction =
  | "view"
  | "read"
  | "create"
  | "edit"
  | "publish"
  | "delete"
  | "manage"
  | "approve"
  | "configure";

export interface PermissionRow {
  id: string;
  feature: PermissionFeature;
  action: PermissionAction;
  description: string;
}

export interface UserSiteRoleRow {
  id: string;
  user_id: string;
  site_id: string;
  role_id: string;
  created_at: string;
}

// ── Admin Site Memberships ──────────────────────────────────────────────

export interface AdminSiteMembershipRow {
  id: string;
  admin_user_id: string;
  site_id: string;
  created_at: string;
}

// ── Integrations ───────────────────────────────────────────────────────

type IntegrationCategory =
  | "affiliate_network"
  | "analytics"
  | "email"
  | "storage"
  | "bot_protection"
  | "search"
  | "cdn"
  | "other";

export interface IntegrationProviderRow {
  id: string;
  key: string;
  name: string;
  category: IntegrationCategory;
  description: string;
  config_schema: Record<string, unknown>;
  is_builtin: boolean;
  created_at: string;
}

export interface SiteIntegrationRow {
  id: string;
  site_id: string;
  provider_key: string;
  is_enabled: boolean;
  config: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

// ── Media Library ───────────────────────────────────────────────────────

export interface MediaRow {
  id: string;
  site_id: string;
  public_key: string;
  url: string;
  filename: string | null;
  content_type: string | null;
  size_bytes: number | null;
  alt_text: string | null;
  variants: Record<
    string,
    { url: string; width: number; height: number; size: number; content_type: string }
  > | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

// ── Site Presentations (DB-authoritative header/footer design) ──────────

export type SitePresentationStatus = "draft" | "published" | "archived";

export interface SitePresentationRow {
  id: string;
  site_id: string;
  status: SitePresentationStatus;
  version: number | null;
  header_variant: string | null;
  footer_variant: string | null;
  header_config: Record<string, unknown>;
  footer_config: Record<string, unknown>;
  header_tokens: Record<string, unknown>;
  created_by: string | null;
  published_by: string | null;
  created_at: string;
  updated_at: string;
  published_at: string | null;
}
