import type { SiteDefinition } from "@/config/site-definition";
import type { AuthorRow, ContentRow, ProductRow } from "@/types/database";
import { parseDocument, DomUtils } from "htmlparser2";
import type { Element, Text, ChildNode } from "domhandler";
import { headers } from "next/headers";
import { NONCE_HEADER } from "@/lib/csp";
import { safeJsonLdString } from "@/lib/safe-json-ld";
import { hasUsableAffiliateUrl } from "@/lib/affiliate-url";

interface JsonLdProps {
  data: Record<string, unknown>;
}

/**
 * JSON-LD `<script>` block.  Even though `application/ld+json` scripts are
 * not executed by the browser, CSP `script-src` still governs them, so we
 * tag every instance with the per-request nonce generated by middleware
 * (H-10).  Reading `headers()` makes this a Server Component — callers
 * that render it synchronously from another Server Component must `await`
 * the returned promise, which the TSX compiler handles transparently for
 * `async function` components.
 */
export async function JsonLd({ data }: JsonLdProps) {
  const hdrs = await headers();
  const nonce = hdrs.get(NONCE_HEADER) ?? undefined;
  return (
    <script
      type="application/ld+json"
      nonce={nonce}
      dangerouslySetInnerHTML={{ __html: safeJsonLdString(data) }}
    />
  );
}

/** Organization schema for homepage */
export function organizationJsonLd(site: SiteDefinition) {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: site.name,
    url: `https://${site.domain}`,
    description: site.brand.description,
    contactPoint: {
      "@type": "ContactPoint",
      email: site.brand.contactEmail,
      contactType: "customer support",
    },
  };
}

/** WebSite schema for homepage */
export function webSiteJsonLd(site: SiteDefinition) {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: site.name,
    url: `https://${site.domain}`,
    description: site.brand.description,
    inLanguage: site.language,
  };
}

interface SoftwareApplicationInput {
  name: string;
  description: string;
  url: string;
  applicationCategory?: string;
  operatingSystem?: string;
}

/** SoftwareApplication schema for free tools / calculators */
export function softwareApplicationJsonLd(input: SoftwareApplicationInput) {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: input.name,
    description: input.description,
    url: input.url,
    applicationCategory: input.applicationCategory ?? "SoftwareApplication",
    operatingSystem: input.operatingSystem ?? "Any",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
  };
}

/** BreadcrumbList schema */
export function breadcrumbJsonLd(site: SiteDefinition, items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: `https://${site.domain}${item.path}`,
    })),
  };
}

/** Person/Author schema — supports E-E-A-T signals (photo, credentials, URL). */
export function personJsonLd(site: SiteDefinition, author: AuthorRow): Record<string, unknown> {
  const data: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Person",
    name: author.name,
    url: `https://${site.domain}/author/${author.slug}`,
    description: author.bio || undefined,
    jobTitle: author.credentials || undefined,
    knowsAbout: author.expertise.length > 0 ? author.expertise : undefined,
  };

  if (author.photo_url) {
    data.image = author.photo_url;
  }

  if (Object.keys(author.social_links).length > 0) {
    data.sameAs = Object.values(author.social_links).filter(Boolean);
  }

  return data;
}

/** Article schema for content pages */
export function articleJsonLd(
  site: SiteDefinition,
  content: ContentRow,
  author?: AuthorRow | null,
) {
  const data: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: content.title,
    description: content.excerpt || content.title,
    datePublished: content.created_at,
    dateModified: content.updated_at || content.created_at,
    author: author
      ? personJsonLd(site, author)
      : content.author
        ? { "@type": "Person", name: content.author }
        : { "@type": "Organization", name: site.name },
    publisher: {
      "@type": "Organization",
      name: site.name,
      url: `https://${site.domain}`,
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": `https://${site.domain}/${content.type}/${content.slug}`,
    },
    inLanguage: site.language,
  };

  if (content.featured_image) {
    data.image = content.featured_image;
  }

  return data;
}

/** Review schema for review-type content */
export function reviewJsonLd(
  site: SiteDefinition,
  content: ContentRow,
  product?: ProductRow,
  author?: AuthorRow | null,
) {
  const base: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Review",
    headline: content.title,
    description: content.excerpt || content.title,
    datePublished: content.created_at,
    dateModified: content.updated_at || content.created_at,
    author: author
      ? personJsonLd(site, author)
      : content.author
        ? { "@type": "Person", name: content.author }
        : { "@type": "Organization", name: site.name },
    publisher: {
      "@type": "Organization",
      name: site.name,
      url: `https://${site.domain}`,
    },
    inLanguage: site.language,
  };

  if (product) {
    base.itemReviewed = {
      "@type": "Product",
      name: product.name,
      ...(product.image_url ? { image: product.image_url } : {}),
      ...(product.description ? { description: product.description } : {}),
    };
    if (product.score !== null) {
      base.reviewRating = {
        "@type": "Rating",
        ratingValue: product.score,
        bestRating: 10,
        worstRating: 0,
      };
    }
  } else {
    // Always include itemReviewed per schema.org spec — fall back to a
    // generic Thing using the content title when no product is linked.
    base.itemReviewed = {
      "@type": "Thing",
      name: content.title,
    };
  }

  return base;
}

/** Recursively extract plain text from a DOM node */
function getTextContent(node: ChildNode): string {
  if (node.type === "text") return (node as Text).data;
  if (node.type === "tag") {
    return (node as Element).children.map(getTextContent).join("");
  }
  return "";
}

const HEADING_TAGS = new Set(["h2", "h3", "h4"]);

/**
 * FAQ schema — extracts Q&A pairs from HTML content.
 * Uses htmlparser2 to robustly parse HTML and find heading+content pairs
 * where the heading text ends with "?". Handles nested markup, varied
 * heading levels (h2-h4), and whitespace between elements.
 */
export function faqJsonLd(html: string): Record<string, unknown> | null {
  const doc = parseDocument(html);
  const topLevel = DomUtils.getChildren(doc);
  const pairs: { question: string; answer: string }[] = [];

  for (let i = 0; i < topLevel.length; i++) {
    const node = topLevel[i];
    if (node!.type !== "tag") continue;
    const el = node as Element;

    if (!HEADING_TAGS.has(el.tagName)) continue;

    const headingText = getTextContent(el).trim();
    if (!headingText.endsWith("?")) continue;

    // Collect all sibling content until the next heading as the answer
    const answerParts: string[] = [];
    for (let j = i + 1; j < topLevel.length; j++) {
      const sibling = topLevel[j];
      if (sibling!.type === "tag" && HEADING_TAGS.has((sibling as Element).tagName)) break;
      const text = getTextContent(sibling!).trim();
      if (text) answerParts.push(text);
    }

    const answer = answerParts.join(" ");
    if (answer) {
      pairs.push({ question: headingText, answer });
    }
  }

  if (pairs.length === 0) return null;

  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: pairs.map((pair) => ({
      "@type": "Question",
      name: pair.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: pair.answer,
      },
    })),
  };
}

/** Product schema */
export function productJsonLd(site: SiteDefinition, product: ProductRow) {
  const productUrl = `https://${site.domain}/r/${product.slug}`;
  const data: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Product",
    "@id": productUrl,
    name: product.name,
    description: product.description || product.name,
    url: productUrl,
  };

  if (product.image_url) {
    data.image = product.image_url;
  }

  // AggregateRating helps rich snippets show star ratings in SERPs.
  // reviewCount defaults to 1 when only the editorial review is available.
  if (product.score !== null) {
    data.aggregateRating = {
      "@type": "AggregateRating",
      ratingValue: product.score,
      bestRating: 10,
      worstRating: 0,
      reviewCount: 1,
    };
  }

  if (product.price_amount || product.price) {
    const numericPrice =
      product.price_amount ??
      (product.price ? Number(product.price.replace(/[^0-9.]/g, "")) : undefined);
    if (numericPrice && numericPrice > 0) {
      data.offers = {
        "@type": "Offer",
        price: numericPrice,
        priceCurrency: product.price_currency || "USD",
        availability: "https://schema.org/InStock",
        ...(hasUsableAffiliateUrl(product.affiliate_url) ? { url: product.affiliate_url } : {}),
        // `merchant` is the retailer we link to (e.g. "Amazon"), which is
        // the schema.org Offer *seller* — NOT the product's manufacturer
        // brand. Emitting it as `brand` produced incorrect rich results
        // (every product branded "Amazon").
        ...(product.merchant
          ? { seller: { "@type": "Organization", name: product.merchant } }
          : {}),
      };
    }
  }

  if (product.score !== null) {
    data.review = {
      "@type": "Review",
      reviewRating: {
        "@type": "Rating",
        ratingValue: product.score,
        bestRating: 10,
        worstRating: 0,
      },
      author: { "@type": "Organization", name: site.name },
    };
  }

  return data;
}

/** ItemList schema for ranked "best X" listicles and comparison pages */
export function itemListJsonLd(
  site: SiteDefinition,
  name: string,
  products: ProductRow[],
): Record<string, unknown> | null {
  if (products.length === 0) return null;

  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name,
    itemListElement: products.map((product, index) => ({
      "@type": "ListItem",
      position: index + 1,
      item: {
        "@type": "Product",
        "@id": `https://${site.domain}/r/${product.slug}`,
        name: product.name,
      },
    })),
  };
}
