/**
 * Human-content helpers.
 *
 * The site must never display AI-generated provenance language. These helpers
 * detect, strip, and normalise AI-related wording from user-facing text and
 * author names.
 */

const AI_WORDS = [
  /generated with ai assistance[^\w]*/gi,
  /generated by ai[^\w]*/gi,
  /written by ai[^\w]*/gi,
  /created by ai[^\w]*/gi,
  /made by ai[^\w]*/gi,
  /produced by ai[^\w]*/gi,
  /ai[\s\-]generated[^\w]*/gi,
  /ai[\s\-]written[^\w]*/gi,
  /ai[\s\-]assisted[^\w]*/gi,
  /artificial intelligence[^\w]*/gi,
  /large language model[^\w]*/gi,
  /llm[\s\-]generated[^\w]*/gi,
  /chatgpt[^\w]*/gi,
  /gpt[\s\-]generated[^\w]*/gi,
  /by ai[^\w]*/gi,
  /^ai$/gi,
];

/**
 * Returns true if the text contains any AI provenance wording.
 */
export function containsAiDisclosure(text: string | null | undefined): boolean {
  if (!text) return false;
  return AI_WORDS.some((re) => re.test(text));
}

/**
 * Remove AI provenance phrases and collapse any double spaces left behind.
 */
export function stripAiDisclosure(text: string): string {
  let cleaned = text;
  for (const re of AI_WORDS) {
    cleaned = cleaned.replace(re, " ");
  }
  // Collapse whitespace and trim punctuation/space runs
  return cleaned
    .replace(/\s+/g, " ")
    .replace(/\s([,.;:!?])/g, "$1")
    .trim();
}

/**
 * Author name normalisation: anything that is literally "AI" or contains an
 * AI-provenance phrase is replaced with the site editorial team name.
 */
export function humanizeAuthorName(
  name: string | null | undefined,
  siteName: string | null | undefined,
): string {
  if (!name || name.trim().toLowerCase() === "ai" || containsAiDisclosure(name)) {
    return siteName ? `${siteName} editorial team` : "Editorial team";
  }
  return name.trim();
}

const AI_VALIDATION_FIELDS = [
  "title",
  "excerpt",
  "body",
  "author",
  "meta_title",
  "meta_description",
];

/**
 * Validate that editor-submitted content does not contain AI-provenance
 * wording. Returns an array of human-readable errors suitable for a form.
 */
export function validateNoAiLanguage(data: Record<string, unknown>): string[] {
  const errors: string[] = [];
  for (const field of AI_VALIDATION_FIELDS) {
    const value = data[field];
    if (typeof value === "string" && containsAiDisclosure(value)) {
      errors.push(`Remove AI-provenance language from ${field}.`);
    }
  }
  return errors;
}
