/**
 * A153: Disposable / throwaway email domain blocker.
 *
 * Blocks well-known disposable email services at signup/subscribe time to
 * prevent abuse via throwaway addresses (coupon farming, fake referrals,
 * newsletter spam). The list covers the most-abused providers; for a
 * comprehensive block use an API like Kickbox or MailCheck.ai in conjunction.
 *
 * Rules:
 *   - Block exact domain matches (e.g. "mailinator.com")
 *   - Block known subdomain patterns of abuse (e.g. anything under "guerrillamail.info")
 *   - Allowlist is the OPPOSITE approach — everything not in the blocklist is allowed
 *
 * Sources: https://github.com/disposable-email-domains/disposable-email-domains
 */

// A153-01: Expanded curated blocklist of the most-abused disposable email providers.
// Sources: disposable-email-domains/disposable-email-domains, manual abuse reports.
const DISPOSABLE_DOMAINS = new Set([
  // Mailinator family
  "mailinator.com",
  "mailinater.com",
  "mailinator2.com",
  "mailinator.net",
  "trashmail.at",
  "trashmail.com",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trash-mail.at",
  "trashmail.ws",
  // Guerrilla Mail
  "guerrillamail.com",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "grr.la",
  "spam4.me",
  // 10 Minute Mail family
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "10minutemail.co.uk",
  "10minemail.com",
  "tempr.email",
  "temp-mail.org",
  "tempmail.com",
  "tempmail.net",
  "tempinbox.com",
  "dispostable.com",
  // Throwam / YopMail
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "yopmail.gq",
  "cool.fr.nf",
  "jetable.fr.nf",
  "nospam.ze.tc",
  "nomail.xl.cx",
  "mega.zik.dj",
  "speed.1s.fr",
  "courriel.fr.nf",
  "moncourrier.fr.nf",
  // Sharklasers / Guerrilla variants
  "sharklasers.com",
  "guerrillamail.biz",
  "guerrillamail.de",
  "spam.la",
  "spam.su",
  // Misc popular disposables
  "fakeinbox.com",
  "fakeinbox.net",
  "throwam.com",
  "throwam.net",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "maildrop.cc",
  "mailnull.com",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",
  "crap.handcrafted.jp",
  "einrot.com",
  "fleckens.hu",
  "spamevader.com",
  "throwaway.email",
  "gishpuppy.com",
  "mytrashmail.com",
  "mt2009.com",
  "mt2014.com",
  "sogetthis.com",
  "spamoff.de",
  "getonemail.com",
  "getonemail.net",
  "jetable.com",
  "jetable.net",
  "jetable.org",
  "nomail.com",
  "nomail2me.com",
  "objectmail.com",
  "ownmail.net",
  "pookmail.com",
  "safetymail.info",
  "spamdecoy.net",
  "spamfree24.org",
  "spammotel.com",
  "spamtrail.com",
  "tempalias.com",
  "tempemail.biz",
  "tempemail.com",
  "tempemail.net",
  "tempomail.fr",
  "tempymail.com",
  "junk.to",
  "kurzepost.de",
  "regbypass.com",
  "rmqkr.net",
  "royal.net",
  "spamcon.org",
  "veryrealemail.com",
  "webm4il.info",
  "zoemail.org",
  // Nada / Nada Email
  "nada.email",
  "nadaemail.com",
  // Inboxkitten
  "inboxkitten.com",
  // Burner Mail
  "burnermail.io",
  // A153-01: additional high-abuse domains
  "mailnesia.com",
  "guerrillamail.xyz",
  "tempail.com",
  "emailondeck.com",
  "mohmal.com",
  "mohmal.in",
  "mohmal.tech",
  "emailfake.com",
  "crazymailing.com",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.de",
  "fleckens.com",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
  "harakirimail.com",
  "minutemail.com",
  "tempmailo.com",
  "temp-mail.io",
  "temp-mail.de",
  "emailnax.com",
  "dropmail.me",
  "tmail.ws",
  "moakt.ws",
  "moakt.co",
  "mailsac.com",
  "mailcatch.com",
  "binkmail.com",
  "suremail.info",
  "spambox.us",
  "anonymbox.com",
  "mailforspam.com",
  "tempmailaddress.com",
  "mail-temporaire.fr",
  "tmpmail.net",
  "tmpmail.org",
  "getairmail.com",
  "filzmail.com",
  "trashymail.com",
  "trashymail.net",
  "mailexpire.com",
  "tempmailer.com",
  "tempmailer.de",
  "tempmails.net",
  "receiveee.com",
  "inboxalias.com",
  "emailisvalid.com",
  "33mail.com",
  "maildax.com",
  "disbox.net",
  "disbox.org",
  "sharklasers.org",
  "mailtemp.info",
  "meltmail.com",
  "mailzilla.com",
  "mailzilla.org",
  "deadaddress.com",
  "tmail.com",
  "throwawayemailaddress.com",
  "mailslurp.com",
  "mailhero.io",
  "tempemails.io",
  "disposableinbox.com",
  "mailme.lv",
  "yopmail.org",
  "tempsky.com",
  "mailpoof.com",
  "throwmail.com",
  "getnada.com",
  "mailgw.com",
  "emailsensei.com",
  "spamwc.de",
  "trashcanmail.com",
  "fakemailgenerator.com",
  "mailseal.de",
  "mail72.com",
  "mailtothis.com",
  "mailinator.us",
  "baxomale.ht.cx",
  "bobmail.info",
  "clrmail.com",
  "devnullmail.com",
  "dump-email.info",
  "dumpandjunk.com",
  "e4ward.com",
  "emailigo.de",
  "emailmiser.com",
  "emailthe.net",
  "emailwarden.com",
  "evopo.com",
  "fastacura.com",
  "filzmail.com",
  "fixmail.tk",
  "flyspam.com",
  "get1mail.com",
  "getairmail.cf",
  "getairmail.ga",
  "getairmail.gq",
  "getairmail.ml",
  "getairmail.tk",
  "hidemail.de",
  "incognitomail.org",
  "instantemailaddress.com",
  "jetable.pp.ua",
  "kasmail.com",
  "koszmail.pl",
  "lhsdv.com",
  "lookugly.com",
  "lortemail.dk",
  "lr78.com",
  "maileater.com",
  "mailexpire.com",
  "mailfreeonline.com",
  "mailimate.com",
  "mailmoat.com",
  "mailnator.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailtemp.net",
  "mailtothis.com",
  "mailzilla.com",
  "mezimages.net",
  "mfsa.ru",
  "mintemail.com",
  "misterpinball.de",
  "mmmmail.com",
  "mx0.wwwnew.eu",
  "mytempemail.com",
  "nervmich.net",
  "nobulk.com",
  "noclickemail.com",
  "nogmailspam.info",
  "nomail.pw",
  "nomail.xl.cx",
  "nospam.wins.com.br",
  "no-spam.ws",
  "nowmymail.com",
  "nurfuerspam.de",
  "nus.edu.sg",
  "oneoffemail.com",
  "onewaymail.com",
  "otherinbox.com",
  "owlpic.com",
  "proxymail.eu",
  "rcpt.at",
  "reallymymail.com",
  "recode.me",
  "s0ny.net",
  "safe-mail.net",
  "safetypost.de",
  "shieldedmail.com",
  "shiftmail.com",
  "skeefmail.com",
  "slaskpost.se",
  "slipry.net",
  "sofimail.com",
  "sofort-mail.de",
  "softpls.asia",
  "sogetthis.com",
  "spamavert.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spamcero.com",
  "spamday.com",
  "spamex.com",
  "spamfighter.cf",
  "spamfighter.ga",
  "spamfighter.gq",
  "spamfighter.ml",
  "spamfighter.tk",
  "spamfree.eu",
  "spamgoes.in",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spaml.de",
  "spamoff.de",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthis.co.uk",
  "spamtrap.ro",
  "spamtrail.com",
  "spamwc.de",
  "supermailer.jp",
  "suremail.info",
  "teleworm.com",
  "thankyou2010.com",
  "thisisnotmyrealemail.com",
  "throwawaymail.com",
  "tittbit.in",
  "trashdevil.com",
  "trashdevil.de",
  "trashemail.de",
  "trashmailer.com",
  "trashymail.com",
  "uggsrock.com",
  "wegwerfadresse.de",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "wuzupmail.net",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xjoi.com",
  "xoxy.net",
  "yep.it",
  "yogamaven.com",
  "yuurok.com",
  "zehnminutenmail.de",
  "zippymail.info",
  // Apple Hide My Email domains (not disposable but sometimes used for spam)
  // — do NOT block privaterelay.appleid.com (it's a legitimate forwarding service)
]);

/**
 * Returns true if the given email domain is a known disposable provider.
 *
 * @param email - A normalized (lowercased) email address.
 */
function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf("@");
  if (at === -1) return false;
  const domain = email.slice(at + 1).toLowerCase();

  // Check the domain and all its parent suffix domains (e.g., sub.mailinator.com -> checks sub.mailinator.com and mailinator.com)
  const parts = domain.split(".");
  for (let i = 0; i < parts.length - 1; i++) {
    const parent = parts.slice(i).join(".");
    if (DISPOSABLE_DOMAINS.has(parent)) return true;
  }

  return false;
}

/**
 * Returns an error message if the email is disposable, or null if it's allowed.
 * Use at signup/subscribe endpoints.
 */
export function validateNotDisposable(email: string): string | null {
  if (isDisposableEmail(email)) {
    return "Please use a permanent email address. Disposable email services are not accepted.";
  }
  return null;
}
