-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 2026071901: add responsive variants to media library
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Stores the optimized responsive image variants generated by the upload
-- finalize pipeline (thumb/small/medium/master WebP, optional AVIF).
--
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE public.media
  ADD COLUMN IF NOT EXISTS variants jsonb;
